### ISSUE TITLE
Game crashes when interacting with ether shop blocks (Fabric 1.20.1)

### ISSUE THREAD

**Issue by ghost** [glisco03/numismatic-overhaul#117] opened 2023-12-19 02:16 UTC
Log: https://mclo.gs/OhH4SJO

**Comment by JAYDEMITE** [comment] 2023-12-25 03:08
Same issue. No idea why mclogs says vanilla crash report. Many mods were used but seems to be entirely
`java/lang/NoSuchFieldError: shop`
https://mclo.gs/QN7tdM8

**Comment by Noaaan** [comment] 2023-12-25 07:33
This is a known issue with Fabric Loader 0.15.0, and is the same issue as #115. 1.20.1 not receiving a backport is an oversight. 
You can temporarily mitigate this by downgrading loader to 0.14.x  any version in that range should be fine

**Comment by Xplodin** [comment] 2023-12-28 02:34
> This is a known issue with Fabric Loader 0.15.0, and is the same issue as #115. 1.20.1 not receiving a backport is an oversight. You can temporarily mitigate this by downgrading loader to 0.14.x any version in that range should be fine

will this be fixed?

**Comment by Noaaan** [comment] 2023-12-29 09:38
yes

**Comment by Xplodin** [comment] 2023-12-30 10:48
> yes

im no developer, but how hard would this be to fix?
Ill personally send you $15 for an updated jar on curseforge if its done within a week :) I hope im not undercutting the time itd take to do the update, but ill promise you that $15 will be yours, I may be an internet rando but this mod it vital in my modpack.

**Comment by Noaaan** [comment] 2023-12-30 11:11
The issue is simply removing an annotation and rebuilding the jar. The main challenge is releasing it, as currently I am out of country and would need to make a manual release vs. using our tooling to do so (plus I would need to actually install Minecraft + Fabric on my laptop for testing). 
Fortunately today is looking promising in terms of available time. Will try to see if I can't get it done before the new year.

**Comment by Xplodin** [comment] 2023-12-31 09:06
> The issue is simply removing an annotation and rebuilding the jar. The main challenge is releasing it, as currently I am out of country and would need to make a manual release vs. using our tooling to do so (plus I would need to actually install Minecraft + Fabric on my laptop for testing). Fortunately today is looking promising in terms of available time. Will try to see if I can't get it done before the new year.

Hey I updated the jar and got a working copy out in a pull request.
:) happy holidays. I hope this helps

**Comment by Noaaan** [comment] 2023-12-31 10:14
Should be fixed as of 0.2.12. Thanks for being patient

**Closed as completed by Noaaan** 2023-12-31 10:14 UTC
Labels: priority: high, status: confirmed, status: scheduled
