### ISSUE TITLE
Librarian trades are glitched

### ISSUE THREAD

**Issue by Looxond** [glisco03/numismatic-overhaul#61] opened 2022-12-04 02:48 UTC
Books with more than 2 enchantments (up to 4 from what ive seen)
How to recreate

-Get a villager and turn it into a librarian
-Enjoy

No starter trades aka no paper or bookshelves trades to further progress
How to recreate

-Same as above
![image](https://user-images.githubusercontent.com/29359853/205471664-11a08a1f-8dc1-4170-b76a-c17a3ca4ca10.png)
![image](https://user-images.githubusercontent.com/29359853/205471677-015846db-1383-4afa-921f-77fa1f268bc9.png)

**Comment by Noaaan** [comment] 2022-12-04 03:35
You must have gotten both really lucky and at the sime time unlucky, since the librarian does have trades which do give you coins. See the image below.

As for the books fairly regularly containing more enchantments per book, this is intended behaviour. In contrast to vanilla randomly grabbing enchantments from the games registry, we "use" the Enchantment Table when creating our books, leading to more interesting results. The balance here could be up for debate, but this is something we are aware of and currently we do not believe it is an issue. 


![image](https://user-images.githubusercontent.com/4163353/205472664-c801e5b3-550f-44a6-9589-b71ca9ecd7ad.png)

**Comment by Looxond** [comment] 2022-12-05 15:37
Is there a way for me to disable or change such behavior? I honestly don't mind the extra spice in those trades but i would  love to keep vanilla trades if possible since books with multiple enchants have the potential to be OP but its very annoying getting a books with enchants that ruin an armor piece and makes it more expensive to enchant.

Not to mention most books you get look like this "Sharpness 3, Piercing 2, Flame" 

I also don't want to be re rolling for the perfect book for hours, getting a single enchantment makes re rolling less annoying since you don't have to worry about more factors than usual.

Also why isnt this mentioned in the curseforge page at all?

**Comment by Noaaan** [comment] 2022-12-05 15:57
Villagers do offer enchanted books with single enchantments. 

All of the documentation regarding configuring Numismatic Overhaul is available at our wiki: https://docs.wispforest.io/numismatic-overhaul/home/
This is linked on our CurseForge page.

If you simply wish to disable custom villager trades, you can simply disable them in the config file.

For now I will close this issue, as the villagers arent really glitched.

**Closed as completed by Noaaan** 2022-12-05 15:57 UTC
