### ISSUE TITLE
NoSuchFieldError: FORMAT

### ISSUE THREAD

**Issue by eatenpancreas** [glisco03/numismatic-overhaul#121] opened 2024-01-07 04:03 UTC
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: FORMAT
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25)
Caused by: java.lang.NoSuchFieldError: FORMAT
	at net.minecraft.class_1799.<clinit>(class_1799.java:133)
	at net.minecraft.class_3727.<clinit>(class_3727.java:16)
	at net.minecraft.class_3726.method_16194(class_3726.java:10)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028)
	at net.minecraft.class_2248.method_9579(class_2248.java:309)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1281)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1185)
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.server.Main.main(Main.java:109)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 4 more
```

This occurs when: 
- running a fabric server with only numismatic overhaul and owo-lib installed
- just owo-lib works
- minecraft version 1.20.1
- newest fabric version
- happens for both linux and mac

**Comment by Dragon-Seeker** [comment] 2024-01-07 04:28
Duplicate of https://github.com/wisp-forest/numismatic-overhaul/issues/115 either update the Numismatic version or downgrading the loader version

**Comment by Noaaan** [comment] 2024-01-07 10:50
Were you using 0.2.12 at the time? That version should fix this issue

**Closed as completed** 2024-01-07 17:48 UTC
Labels: type: duplicate
