### ISSUE TITLE
Shop crashes the game

### ISSUE THREAD

**Issue by Dormdude** [glisco03/numismatic-overhaul#97] opened 2023-08-04 16:14 UTC
When trying to open the shop it crashes the game. I thought it might be a compatibility issue so I disabled every other mod except Numismatic Overhaul and it's requirement, but that created a new issue of the game crashes trying to launch. if i create a new modlist with curse and only add Numismatic Overhaul and the requirement it works fine. While extremely weird it's not uncommon in my experience with Minecraft modding. Are there any known compatibility issues?

**Comment by BasiqueEvangelist** [comment] 2023-08-04 16:15
Can you send the actual crash report? We have no idea what compatibility issue it is if we don't know what the error even is

**Comment by Dormdude** [comment] 2023-08-04 17:09
Sorry I didn't even think about that.
[crash-2023-08-04_13.08.11-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/12262998/crash-2023-08-04_13.08.11-client.txt)

**Comment by pen9go** [comment] 2023-08-08 01:07
I have this same issue. Just a hunch, but it might be supplementaries, supplementaries squared, or farmer's delight. I'll test it when I get a chance but if you have those mods it might be one of those. Also the crash is client side, not server side, if that helps in anyway for addressing the problem. It just crashed my instance of minecraft and not the server I was playing on.

**Comment by Elska85** [comment] 2023-08-12 18:08
Game crashes client side on shop, I believe this to be the cause of farmer's delight and or tiered mod.

**Comment by gliscowo** [comment] 2023-08-19 21:37
Could somebody here try to isolate the specific mod which is causing the problem? This is clearly a compatiblity issue, and it's much easier for somebody who already has a crashing setup to figure out which mod precisely is causing it than it is for us to rebuild the entire pack first

Cheers

**Comment by Dormdude** [comment] 2023-08-19 22:12
That mod list is long gone

**Comment by OneLoneFox** [comment] 2023-09-18 05:41
Hmmm so I'm having the same issue but it's even worse, I get the same crash log ([crash-2023-09-18_00.28.29-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/12644859/crash-2023-09-18_00.28.29-client.txt)) as above:


> Sorry I didn't even think about that. [crash-2023-08-04_13.08.11-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/12262998/crash-2023-08-04_13.08.11-client.txt)

But it's not limited to opening the shop, trying to open any config menu from modmenu that uses owolib also creates the exact same crash log, I've been looking in the wrong place the entire day because the only clue in the crash log refers to owolib being unable to draw something somewhere.

Now... I don't have supplementaries nor farmer's delight installed but I do have tieredZ which I have tried disabling with no positive results so unless I disable my entire mod list one by one I don't think finding the cause is going to be easy.

**Comment by OneLoneFox** [comment] 2023-09-21 20:16
Ok so I ended up reinstalling the entire modpack one mod at a time trying to make it crash and it didn't but turns out I forgot to install a single mod which is "Sodium Extra" then after configuring the modpack and looking for new mods to expand it I reinstalled it and didn't touch configs again until I found the same crash today and after searching everywhere on github I stumbled into an issue on a completely unrelated mod with the exact same crash log, turns out the issue is caused by a compat issue between [**sodium extra** and **owo-lib**](https://github.com/wisp-forest/gadget/issues/30#issuecomment-1699965037) I disabled sodium extra and poof, the crash is gone...
Now, I have to mention that I have very specific versions of sodium and such because there is another issue with the **create** mod which doesn't support sodium >=0.5 so in my spare time I might just check newer versions without the create mod and if the issue exists on newer version I will submit an issue to sodium extra's repo.

You can close this issue now as it's not numismatic's fault.

**Closed as not planned** 2023-10-30 01:04 UTC
Labels: type: bug, type: compatibility, priority: normal
