### ISSUE TITLE
Client crashes when oppening shop (not charm incompatibility)

### ISSUE THREAD

**Issue by Allomere** [glisco03/numismatic-overhaul#63] opened 2022-12-15 07:36 UTC
[crash-2022-12-15_03.44.36-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/10234477/crash-2022-12-15_03.44.36-client.txt)
I dont have charm installed on my server, but when players try to open a shop it crashes their client

**Comment by Noaaan** [comment] 2022-12-15 07:42
Duplicate of #62 
We have already fixed it, and it is planned for next release

**Comment by gliscowo** [comment] 2022-12-17 23:48
Fixed in [0.2.6](https://modrinth.com/mod/numismatic-overhaul/version/RH84wQRG)

**Closed as completed by gliscowo** 2022-12-17 23:48 UTC
Labels: type: bug, type: duplicate
