### ISSUE TITLE
[Client Crash] - Wandering Villager - Resized Minecraft Window while in Trader Menu - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [glisco03/numismatic-overhaul#55] opened 2022-11-17 21:00 UTC
Client [Crash Report](https://gist.github.com/SpigotDE/7aad561aaefe9664822234278a0df22f)
Client [latest.log](https://gist.github.com/SpigotDE/12a0015c0c2039ee703f0a6e22ea0605)

**Comment by Noaaan** [comment] 2022-11-17 22:52
Duplicate of #57

**Closed as completed by Noaaan** 2022-11-17 22:52 UTC
Labels: type: duplicate
