### ISSUE TITLE
Crash Opening Shops & Piggy Bank

### ISSUE THREAD

**Issue by RyanSalad** [glisco03/numismatic-overhaul#112] opened 2023-11-30 11:04 UTC
Minecraft 1.19.2
Fabric 0.15.0
Numismatic Overhaul 0.2.9
owo-lib 0.9.3

As the title says, the game crashes every time I open any containers from Numismatic Overhaul
Here's the crash report as well:
[crash-2023-11-30_04.45.47-server.txt](https://github.com/wisp-forest/numismatic-overhaul/files/13511861/crash-2023-11-30_04.45.47-server.txt)

**Comment by Noaaan** [comment] 2023-11-30 11:15
Duplicate of #49 
Installing Charm-Fixer mitigates this problem: https://www.curseforge.com/minecraft/mc-mods/charm-fixer

**Closed as not planned by Noaaan** 2023-11-30 11:15 UTC
Labels: type: duplicate

**Comment by RyanSalad** [comment] 2023-11-30 11:36
> Duplicate of #49 Installing Charm-Fixer mitigates this problem: https://www.curseforge.com/minecraft/mc-mods/charm-fixer

I had decided to bite the bullet and not use Charm, but it started crashing again...
