### ISSUE TITLE
Clientcrash

### ISSUE THREAD

**Issue by TheButterbrotMan** [glisco03/numismatic-overhaul#8] opened 2022-01-31 22:32 UTC
Latest: https://bytebin.lucko.me/BowrGRk1mw

Crash: https://bytebin.lucko.me/823NwFQTrl

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:34
Is definitely a mod incomaptible, but im unable to locate it.

**Comment by gliscowo** [comment] 2022-01-31 22:36
Can you launch with the `-Dmixin.debug.verbose=true` launch argument and get us that log? This would allow us to identify the mixin that is in the stacktrace and thereby possibly find the conflicting mod

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:42
Could also be linked to this crashlog: https://bytebin.lucko.me/n1B2TbY5Fi

EDIT: Im launching at the moment with  -Dmixin.debug.verbose=true

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:43
> Latest: https://bytebin.lucko.me/BowrGRk1mw
> Crash: https://bytebin.lucko.me/823NwFQTrl

Crash happened when interacting with Librarian Villager

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:50
Im unable to get it crashing with -Dmixin.debug.verbose=true.

I will test now again without. I tried it like 4 times before and it crashed everytime, so i dont understand why it does not now.

**Comment by BasiqueEvangelist** [comment] 2022-01-31 22:52
Can you try to reproduce it with MixinTrace (https://www.curseforge.com/minecraft/mc-mods/mixintrace)?

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:53
> Can you try to reproduce it with MixinTrace (https://www.curseforge.com/minecraft/mc-mods/mixintrace)?

Does it work with 1.18?

**Comment by BasiqueEvangelist** [comment] 2022-01-31 22:55
It *should* work with 1.18, as it really only depends on the crash report system

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:58
So, i tried it now with argument, without and with mixintrace and im unable to get it to crash.

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:58
It crashed 6-7 times before and now i does nothing.

**Comment by BasiqueEvangelist** [comment] 2022-01-31 22:59
> So, i tried it now with argument, without and with mixintrace and im unable to get it to crash.

I'm not sure I understand what you said. Did you try it without the argument and with MixinTrace?

**Comment by TheButterbrotMan** [comment] 2022-01-31 22:59
Yes

**Comment by TheButterbrotMan** [comment] 2022-01-31 23:00
I had an similar report on another mod, maybe his fix helps:

https://github.com/LlamaramaTeam/Llamarama/issues/5

**Comment by BasiqueEvangelist** [comment] 2022-01-31 23:03
Very strange that it crashes with MixinTrace. Could you send the log with the launch argument?

> I had an similar report on another mod, maybe his fix helps:
> 
> [LlamaramaTeam/Llamarama#5](https://github.com/LlamaramaTeam/Llamarama/issues/5)

That crash probably isn't related

**Comment by TheButterbrotMan** [comment] 2022-01-31 23:05
> 

Nono, sorry.

Crashing stopped.

It does not crash with MixinTrace, Argument or without Argument. I am unable to reproduce it.

**Comment by BasiqueEvangelist** [comment] 2022-01-31 23:05
> > 
> 
> Nono, sorry.
> 
> Crashing stopped.
> 
> It does not crash with MixinTrace, Argument or without Argument.

Please send the log with the launch argument, even if it doesn't crash

**Comment by TheButterbrotMan** [comment] 2022-01-31 23:30
Crash: https://bytebin.lucko.me/rViuDsC7H7 <--- With Mixin Mod
Latest: https://bytebin.lucko.me/NC9a6dFLK6
Crash: https://bytebin.lucko.me/HB0ERK48dL <--- With Argument
Latest: https://bytebin.lucko.me/qF1q01peYn

**Comment by TheButterbrotMan** [comment] 2022-01-31 23:38
I got it crashing both times, the crash doesnt appear every time. Sometimes it dont crash. You can reproduce it by try to interact with them.

**Comment by gliscowo** [comment] 2022-02-05 13:12
I have been able to track down the mod which causes this and it turns out to be the combination of Crooked Crooks, Survival Plus and possibly a few others. The root cause of the problem is that Survival Plus overwrites a method in the Enchantment Helper without properly declaring that it's doing so, and thereby causes a few other mods' mixins, namely Crooked Crooks, to never actually get triggered and cause an exception. This is something that could happen at an Enchantment Table or a vanilla Librarian as well, as such I'll close this issue as `invalid` for now. For you to fix your trouble I would recommend simply removing Survival Plus if you can, although removing Crooked Crooks might also work but would definitely be less safe
Cheers

**Closed as completed by gliscowo** 2022-02-05 13:12 UTC
Labels: status: invalid

**Comment by TheButterbrotMan** [comment] 2022-02-05 13:52
Wow, thank you. How did you figure that out? I tried this since days.
