### ISSUE TITLE
Server Crash through Watchdog when player trades with Cartographer, happens in singleplayer too. Fabric 1.20.1 v0.2.12

### ISSUE THREAD

**Issue by JAYDEMITE** [glisco03/numismatic-overhaul#131] opened 2024-02-16 00:27 UTC
Removing the mod in singleplayer fixes the crash, haven't tested on server. It seems specific to the Cartographer, as players have been trading with Librarians and Clerics no problem. It occurs when you unlock the first explorer map.
This is the crash report, no other details seem to be available. https://mclo.gs/LNqi7XP

**Comment by Noaaan** [comment] 2024-02-16 00:42
Duplicate of #93

**Closed as not planned by Noaaan** 2024-02-16 00:42 UTC
Labels: type: duplicate
