### ISSUE TITLE
MCA Reborn incompatible with Numismatic Overhaul

### ISSUE THREAD

**Issue by LeDemmers** [glisco03/numismatic-overhaul#88] opened 2023-06-07 02:57 UTC
**Describe the bug**
Mod, "Numismatic Overhaul" which changes currency from Emeralds to a 3 Coin System much like terraria's coin system is not compatible with MCA Reborn

**To Reproduce**
1. Install both MCA and Numismatic Overhaul
2. Attempt to launch game, console open.
3. Get error
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method removeDivisor(I)I in numismatic-overhaul.mixins.json:MCAVillageMixin from mod numismatic-overhaul failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap numismatic-overhaul-refmap.json`
4. Look at it, and understand what is happening.

**Version**
7.5.2-1.19.2, 1.19.2, Fabric 0.14.21
MCA Version, Minecraft version, Modloader
Numismatic ver 0.2.8+1.19

**Latest.log**
[latest.log](https://github.com/wisp-forest/numismatic-overhaul/files/11672063/latest.log)

[Linked Issue](https://github.com/Luke100000/minecraft-comes-alive/issues/675)

**Comment by Noaaan** [comment] 2023-06-11 14:32
Duplicate of #78

**Closed as not planned by Noaaan** 2023-06-11 14:32 UTC
Labels: type: duplicate
