### ISSUE TITLE
(1.19.4) Crash on death

### ISSUE THREAD

**Issue by Overkill77** [glisco03/numismatic-overhaul#87] opened 2023-05-18 22:31 UTC
I got a crash after dying and after inspecting the crash logs, it seems to not be compatible with the mod [Yigd](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)

### Crash log:
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "io.wispforest.owo.config.ConfigSynchronizer.getClientOptions(net.minecraft.class_3222, String)" is null
	at com.glisco.numismaticoverhaul.currency.CurrencyComponent.modify(CurrencyComponent.java:87)
	at com.b1n_ry.yigd.compat.NumismaticOverhaulCompat.setInventory(NumismaticOverhaulCompat.java:50)
	at net.minecraft.class_3222.mdd7adb5$yigd$lambda$onRespawn$1$2(class_3222.java:15423)
	at com.b1n_ry.yigd.Yigd.lambda$onInitialize$6(Yigd.java:295)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$cce000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:3872)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
If theres nothing that can be done, thank you for still trying.

**Comment by gliscowo** [comment] 2023-05-30 17:38
This is essentially a duplicate of wisp-forest/numismatic-overhaul#83, which was just fixed, and as such I'll go ahead and close this a fixed as well
Cheers

**Closed as completed by gliscowo** 2023-05-30 17:38 UTC
