### ISSUE TITLE
Client crash when opening any shop

### ISSUE THREAD

**Issue by AleixCat** [glisco03/numismatic-overhaul#49] opened 2022-11-05 10:24 UTC
[crash-2022-11-05_00.54.54-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/9943544/crash-2022-11-05_00.54.54-client.txt)

Tested with older versions of OWO, still happens.

Tested with previous version 0.2.3, it doesn't crash.

**Comment by Dragon-Seeker** [comment] 2022-11-12 00:02
Such is a problem with Charm and one of its events that it uses for adding buttons to Screens.

Issue report in https://github.com/svenhjol/Charm/issues/878 Github.

**Comment by Dragon-Seeker** [comment] 2022-11-12 00:33
Working Solution is to download this Custom Mod that will fix the issue by disabling any modules that are using the offensive API.
Modrinth: [Link](https://modrinth.com/mod/charm-fixer)
Curseforge: [Link](https://www.curseforge.com/minecraft/mc-mods/charm-fixer)

**Comment by paulhlschr** [comment] 2022-12-03 15:05
I would like to revive this thread, as I am running into the same crash.

Minecraft version:
1.19.2
Quilt loader version:
0.17.6

- Test Environment with Charm/Charm: 
	- Full log: https://mclo.gs/8ZM00IY
	- Crash log: https://mclo.gs/MphYX9F
- Test Environment without Charm/Charm Fixer: 
	- Full log: https://mclo.gs/zoZs9Nr
	- Crash report: https://mclo.gs/nIhLoO4

In both cases the client crashes immediately after right-clicking a shop.

**Comment by Noaaan** [comment] 2022-12-03 15:36
This is not the same crash, and you are using Quilt.
Please open a new issue.

**Comment by arazadaz** [comment] 2023-06-17 22:26
I just recently ran into this. Charm Fixer does indeed fix it though.

**Comment by gliscowo** [comment] 2023-08-19 22:07
Since this problem is not caused by Numismatic and easily worked around using Charm Fixer, I'll go ahead and close the issue

 Cheers

**Closed as not planned by gliscowo** 2023-08-19 22:07 UTC
Labels: status: wontfix, type: compatibility
