### ISSUE TITLE
Crash when booting (1.19.2)

### ISSUE THREAD

**Issue by Pixelidon** [glisco03/numismatic-overhaul#98] opened 2023-08-15 06:27 UTC
Hi, whenever I try to boot my server it crash with this error message. Did I missed something ?

[crash-2023-08-15_08.19.56-server.txt](https://github.com/wisp-forest/numismatic-overhaul/files/12341715/crash-2023-08-15_08.19.56-server.txt)

**Comment by gliscowo** [comment] 2023-08-19 21:28
For one, this issue does not (at least in any obvious manner) seem to be caused by Numismatic, so reporting it here would presumably be redundant either way. On the other hand, our support period for 1.19.2 has ended a long time ago, so sadly we won't be looking into this any further

You can try joining the [Wisp Forest Discord server](https://wispforest.io/discord) so we can maybe see about getting your game to run, but I'll be closing the issue here for the time being

Cheers

**Closed as not planned by gliscowo** 2023-08-19 21:28 UTC
Labels: status: wontfix
