### ISSUE TITLE
Purse stuck to the left side of the screen

### ISSUE THREAD

**Issue by Zano1999** [glisco03/numismatic-overhaul#111] opened 2023-11-04 18:19 UTC
I don't know if it was caused by an incompatibility with another mod or is a bug in 1.20.1 version, but the purse is blocked in the position showed in the image and can't be moved trought settings.

Mod list: https://pastebin.com/WZpEBHy0

![image](https://github.com/wisp-forest/numismatic-overhaul/assets/42555362/a6fdf508-dfd9-4c37-b5f1-e93e9dc16bfa)

**Comment by Noaaan** [comment] 2023-11-05 15:03
This issue is a duplicate of #102, as removing the recipe book breaks the purse position.

**Closed as not planned by Noaaan** 2023-11-05 15:03 UTC
Labels: type: duplicate
