### ISSUE TITLE
every time a mob dies, the game crashes

### ISSUE THREAD

**Issue by LordDecay26** [glisco03/numismatic-overhaul#41] opened 2022-08-07 15:40 UTC
in versions 0.2.1 and 0.2.2 for 1.18.2 that i've tested so far, whenever the wandering trader or his Llamas are killed, it seems that they try to drop the money as an item, which obviously comes out as null and the game crashes.
probably a mod incompatibility, although i cant figure out which mods exactly. information in the crash log is limited.
`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/7/22, 11:32 AM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7960()" because "$$0" is null
	at net.minecraft.class_1297.method_5699(class_1297.java:1816)
	at net.minecraft.class_1297.method_5775(class_1297.java:1811)
	at net.minecraft.class_1308.method_5932(class_1308.java:12611)
	at net.minecraft.class_1308.method_5995(class_1308.java:1261)
	at net.minecraft.class_1314.method_5995(class_1314.java:36)
	at net.minecraft.class_1308.method_5773(class_1308.java:349)
	at net.minecraft.class_1496.method_5773(class_1496.java:594)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1297.method_5699(class_1297.java:1816)
	at net.minecraft.class_1297.method_5775(class_1297.java:1811)
	at net.minecraft.class_1308.method_5932(class_1308.java:12611)
	at net.minecraft.class_1308.method_5995(class_1308.java:1261)
	at net.minecraft.class_1314.method_5995(class_1314.java:36)
	at net.minecraft.class_1308.method_5773(class_1308.java:349)
	at net.minecraft.class_1496.method_5773(class_1496.java:594)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:trader_llama (net.minecraft.class_3986)
	Entity ID: 24111
	Entity Name: Trader Llama
	Entity's Exact location: -3971.10, 65.00, -1218.24
	Entity's Block location: World: (-3972,65,-1219), Section: (at 12,1,13 in -249,4,-77; chunk contains blocks -3984,-64,-1232 to -3969,319,-1217), Region: (-8,-3; contains chunks -256,-96 to -225,-65, blocks -4096,-64,-1536 to -3585,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['GandalfTheDanke'/53, l='ServerLevel[Mysteries of the Void]', x=-3962.10, y=72.00, z=-1209.18]]
	Chunk stats: 5366
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,384,336), Section: (at 0,0,0 in 3,24,21; chunk contains blocks 48,-64,336 to 63,319,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 661436 game time, 228268 day time
	Level name: Mysteries of the Void
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 49358 (now: false), thunder time: 59738 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 656067400 bytes (625 MiB) / 4148166656 bytes (3956 MiB) up to 7683964928 bytes (7328 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7239
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 126783.80
	Virtual memory used (MB): 33908.77
	Swap memory total (MB): 94208.00
	Swap memory used (MB): 240.18
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7328m -Xms256m
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		advancementplaques: Advancement Plaques 1.4.5
		alloygery: Alloygery 2.0+1.18.2
		anthropophagy: Anthropophagy 1.18-5
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.7.78
		autoconfig1u: Auto Config v1 Updated 3.4.0
		besmirchment: Besmirchment 1.18.2-12
			playerabilitylib: Pal 1.5.0
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.3
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		bewitchment: Bewitchment 1.18-23
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		biomemakeover: Biome Makeover 1.18.2-1.4.29
		blast: BLAST 1.9.1
		bookshelf: Bookshelf 13.2.48
		brazier: Brazier 4.0.3
		bwplus: Bewitchment Plus 1.18.2-17
		campfirespawnandtweaks-fabric: Campfire Spawn and Tweaks (Fabric) 1.9
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		castleblocks: CastleBlocks 1.0.0
		cavedust: Cave Dust 1.2.0
			kirin: Kirin UI 1.10.0-beta.2
		ce: Cave Enhancements 1.1.5
		chalk: Chalk 2.0.1+1.18.2
		chat_heads: Chat Heads 0.6.0
		chimes: Chimes 1.1.1
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.36
			fiber: fiber 0.23.0-2
		cosmetic-armor: Cosmetic Armor 1.3.1
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperspores: Creeper Spores 1.8.0
		ctov: ChoiceTheorem's Overhauled Villages 2.9
		customstars: Custom Stars 1.1+1.18.2
		darkness: True Darkness 2.0.91
		darkrites: Dark Rites 1.18.2-1
		decorative_blocks: Decorative Blocks 2.1.0
		dragonloot: DragonLoot 1.1.0
		dual_riders: Dual Riders 1.1.1
		dualwielding: Dual Wielding 1.1.0
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dustrial_decor: Dustrial Decor 0.5
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		dynview: Dynamic View Mod 1.18.2-2.2
		effective: Effective 1.2.1
		elden_horses: Elden Horses 1.0.0+1.18.2
		enchantment_lore: Enchantment Lore 1.2.6-1
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		enchdesc: EnchantmentDescriptions 10.0.4
		enhancedcelestials: Enhanced Celestials 2.0.7
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.5
		equipmentcompare: Equipment Compare 1.2.12
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		farsight: Farsight Mod 1.18-1.9
		fireworkfrenzy: Firework Frenzy 1.9
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.3
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		galosphere: Galosphere 1.18.2-1.1.1
		geckolib3: Geckolib 3.0.54
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		graveyard: The Graveyard 1.9
		grindstonesharpertools-fabric: Grindstone Sharper Tools (Fabric) 2.0
		guardiansgalore: GuardiansGalore 1.18.2-3.0
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		haema: Haema 1.10.1+1.18.2
			satin: Satin 1.7.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.7
		highlighter: Highlighter 1.1.2
		horsestonks: Horse Stonks 1.0.1
		iceberg: Iceberg 1.0.38
		immersive_paintings: Immersive Paintings 0.1.6+1.18.2
		immersive_weathering: Immersive Weathering 2.5.6
		incendium: Incendium + Seed Fix 5.0.4
			seedfix: Seed Fix 1.0.2
		inmis: Inmis 2.6.0-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		itemborders: Item Borders 1.1.5
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 10.1.3.240
		kiwi: Kiwi Lib 6.0.2
		legendarytooltips: Legendary Tooltips 1.2.5
		magehand: Magehand 1.1.2
		mcwfences: Macaw's Fences and Walls 1.0.6
		merchantmarkers: Merchant Markers 1.2.2
		minecraft: Minecraft 1.18.2
		miskatonicmysteries: Miskatonic Mysteries 0.1.3
			bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
			midnightlib: MidnightLib 0.4.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 3.2.3
		myloot: myLoot 2.1.3-1.18
		nbtcrafting: NBT Crafting 2.1.4+mc1.18.2
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 4.2
		nomadbooks: Nomad Books 1.0.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		npcvariety: NPC Variety 2.2.1
		numismatic-overhaul: Numismatic Overhaul 0.2.2+1.18
			stacc: Stacc 1.3.0
		ostoverhaul: Ost Overhaul 0.2.6
		overweight_farming: Overweight Farming 1.18.2-1.5.3-fabric
		owo: oωo 0.7.2-no-cme+1.18
		passiveshield-fabric: Passive Shield (Fabric) 2.3
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pickyourpoison: Pick Your Poison 1.0.8
			org_json_json: json 20211205
		pigeonpost: Pigeon Post 1.0.0
		polymorph: Polymorph 0.0.21-1.18.2
		puzzleslib: Puzzles Lib 3.3.5
		pyrotastic: Pyrotastic 1.18.2+0.0.2
		rare-ice: Rare Ice 0.4.1
		requiem: Requiem 2.0.0-beta.9
			automatone: Automatone 0.7.0
			blabber: Blabber 0.2.0
			chime: Chime 1.2.1
			fiber2cloth: Fiber To Cloth 3.1.1
			impersonate: Impersonate 2.5.0
			locki: Locki 0.7.0
			requiem-core: Requiem-Core 2.0.0-beta.9
			requiemapi: Requiem-API 2.0.0-beta.9
		respawnablepets: Respawnable Pets 1.18-4
		rightclickharvest: Right Click Harvest 2.2.1+1.18
		rpg-hud: RPG-Hud 3.9.2
		rpgstats: RPGStats 4.3.13+1.18.2
			libgui: LibGui 5.4.1+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			server_translations_api: Server Translations API 1.4.12+1.18.2
				packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		shwfox: Shadew's Foxes 1.3+fabric
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		skylorlib: SkyLib 1.3.35
		snowrealmagic: Snow! Real Magic! 4.1.2
		softerhaybales-fabric: Softer Hay Bales (Fabric) 1.9
		spoornpacks: SpoornPacks 4.2.3-1.18.2
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		starterkit-fabric: Starter Kit (Fabric) 3.5
		stylisheffects: Stylish Effects 3.1.0
		sulfurpotassiummod: Sulfur & Potassium 1.1.2
		t_and_t: Towns and Towers - Structure Add-on 1.6
		terrablender: TerraBlender 1.1.0.102
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		tree-hollows: Tree Hollows 1.3.3
			tree-hollows-core: Core 1.3.3
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		vanilla_degus: Vanilla Degus 1.3.0
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 2.2
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		wandering_trapper: Wandering Trapper 1.2.0
		waveycapes: WaveyCapes 1.2.0
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		woof: Woof 1.1.1-1.18
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
			com_github_llamalad7_mixinextras: MixinExtras 0.0.12
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['GandalfTheDanke'/53, l='ServerLevel[Mysteries of the Void]', x=-3962.10, y=72.00, z=-1209.18]]
	Data Packs: vanilla, spoornpacks (incompatible), Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'`

**Comment by Noaaan** [comment] 2022-08-07 18:15
That should not happen in regular Numismatic Overhaul, as the only mobs assigned to drop money are Pillagers. 
Does disabling NO remove the crash?

**Comment by LordDecay26** [comment] 2022-08-07 19:13
i removed the mod and that removed the crash.

**Comment by LordDecay26** [comment] 2022-08-08 01:59
oh, nevermind, it just happened again after 7 hours of testing. and long after this mod was removed. i wouldnt happen to be able to bother you to help me figure out what's causing this, would i?

**Comment by Dragon-Seeker** [comment] 2022-08-08 02:06
Is it the same exact Crash, if not post the latest log

**Comment by LordDecay26** [comment] 2022-08-08 03:26
it's the same exact crash

**Comment by gliscowo** [comment] 2022-08-09 16:08
As this problem is not caused by Numismatic, I'll go ahead and close this issue
Cheers

**Closed as completed by gliscowo** 2022-08-09 16:08 UTC
Labels: status: invalid

**Comment by LordDecay26** [comment] 2022-08-10 07:04
no help finding the source of the issue? :(

**Comment by Noaaan** [comment] 2022-08-10 07:24
There are too many mods in here to simply debug remotely. You will have to dig through your mods themselves and find the culprit. 
I recommend binary searching through your mods: 
![image](https://user-images.githubusercontent.com/4163353/183840250-b4a4a187-e13c-46c0-856f-06926502abe7.png)

**Comment by LordDecay26** [comment] 2022-08-10 08:48
part of the problem is that the issue only occurs with naturally spawned wandering traders, making this process with 100+ mods basically impossible to make work.

**Comment by Noaaan** [comment] 2022-08-10 10:20
I wish I could do more, but for now I do not recommend continuing this conversation on GitHub. 
I recommend asking in the #player-support channel in the [Fabric Discord server](https://discord.gg/KyyxK7Ef) for further support.
