### ISSUE TITLE
Cartographer map for 5 silver locks up the game

### ISSUE THREAD

**Issue by Official-V-Zer0** [glisco03/numismatic-overhaul#147] opened 2024-07-05 22:28 UTC
So I've had an issue with the cartographer villager when he's spawned in (egg or natural) with a trade of 5 silver for a map. It gives him full (or maybe over full) bar and makes everything freeze up, quitting save loops the world needing to be task managered, and when going back on it has rolled back a few actions. So far in my test it's only them. Not even shepherd with a similar trade (5 silver for shears) only gives half bar

here's the log
https://mclo.gs/tLVlrNQ

**Comment by Noaaan** [comment] 2024-07-07 14:04
Are you sure this isn't a duplicate of https://github.com/wisp-forest/numismatic-overhaul/issues/93 ?

**Comment by Official-V-Zer0** [comment] 2024-07-08 09:56
It seems it can be. But then the only fix is to edit the mod itself. So the solution would be to make a compat mod or add Yung's structures in a mod update.

**Comment by Official-V-Zer0** [comment] 2024-07-10 14:10
Ok so the fix for #93 worked but the map wasn't even one that lead to the monument, just an empty map

But the map that came with apprentice level was the one causing the issue trying to generate

**Closed as completed** 2024-11-25 21:55 UTC
