### ISSUE TITLE
Crash when right clicking on a shop block.

### ISSUE THREAD

**Issue by snowjungsungwoo** [glisco03/numismatic-overhaul#77] opened 2023-02-20 04:47 UTC
[1.txt](https://github.com/wisp-forest/numismatic-overhaul/files/10779698/1.txt)

**Comment by Dragon-Seeker** [comment] 2023-02-20 05:27
Duplicate of #49, Install Charm Fixer: (https://www.curseforge.com/minecraft/mc-mods/charm-fixer) to fix the issue

**Comment by snowjungsungwoo** [comment] 2023-02-20 07:23
ty:)

**Closed as completed** 2023-02-20 12:51 UTC
Labels: type: duplicate
